apiVersion: v1
kind: Service
metadata:
  name: backend-api-service
  labels:
    app: backend-api
spec:
  type: ClusterIP  # Ensures the service is internal-only
  selector:
    app: backend-api 
  ports:
    - protocol: TCP
      port: 5000         # Exposed port for external access
      targetPort: 5000   # Port your backend API is listening on inside the pod
