apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webapp-frontend-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: webapp-frontend.internal.com  # Replace with your domain or IP
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: webapp-frontend-service
            port:
              number: 80
