apiVersion: v1
kind: Service
metadata:
  name: webapp-frontend-service
spec:
  type: LoadBalancer  # LoadBalancer to expose the service
  ports:
    - port: 80  # Exposing port 80
      targetPort: 80  # Mapping to container port 80
  selector:
    app: webapp-frontend
